SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE utilizador (
  Email VARCHAR(50) PRIMARY KEY,
  Password VARCHAR(255) NOT NULL,
  Nome VARCHAR(100) NOT NULL,
  Telemovel VARCHAR(12),
  Tipo VARCHAR(20),
  DataNascimento DATE,
  Equipa INT
) ENGINE=InnoDB;

CREATE TABLE simulacao (
  ID_Simulacao INT AUTO_INCREMENT PRIMARY KEY,
  Descricao TEXT,
  Equipa INT NOT NULL,
  Player INT NOT NULL,
  DataHoraInicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Pontuacao DECIMAL(6,2) DEFAULT 0,
  Email VARCHAR(50) NULL,
  FOREIGN KEY (Email) REFERENCES utilizador(Email)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE medicoes_passagens (
  ID_Medicao INT AUTO_INCREMENT PRIMARY KEY,
  Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  SalaOrigem INT,
  SalaDestino INT,
  Marsami INT NOT NULL,
  Status INT NOT NULL,
  ID_Simulacao INT NOT NULL,
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE mensagens (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Sala INT,
  Sensor VARCHAR(20),
  Leitura DECIMAL(6,2),
  TipoAlerta VARCHAR(50),
  Msg VARCHAR(100),
  HoraEscrita TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ID_Simulacao INT NOT NULL,
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE temperatura (
  ID_Temperatura INT AUTO_INCREMENT PRIMARY KEY,
  Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Temperatura DECIMAL(5,2) NOT NULL,
  ID_Simulacao INT NOT NULL,
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE som (
  ID_Som INT AUTO_INCREMENT PRIMARY KEY,
  Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Som DECIMAL(6,2) NOT NULL,
  ID_Simulacao INT NOT NULL,
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ocupacao_labirinto (
  ID_Simulacao INT NOT NULL,
  Sala INT NOT NULL,
  NumeroMarsamisOdd INT DEFAULT 0,
  NumeroMarsamisEven INT DEFAULT 0,
  TriggerCount INT DEFAULT 0,
  UltimaAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_Simulacao, Sala),
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE estado_marsami (
  ID_Simulacao INT NOT NULL,
  Marsami INT NOT NULL,
  SalaAtual INT,
  Paridade VARCHAR(10) NOT NULL,
  Ativo BOOLEAN DEFAULT TRUE,
  UltimaAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_Simulacao, Marsami),
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE score_eventos (
  ID_Score INT AUTO_INCREMENT PRIMARY KEY,
  ID_Simulacao INT NOT NULL,
  Sala INT NOT NULL,
  NumeroOdd INT NOT NULL,
  NumeroEven INT NOT NULL,
  Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_Simulacao) REFERENCES simulacao(ID_Simulacao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

COMMIT;